name: mybinder-env
channels:
  - conda-forge
  - defaults
dependencies:
  - numpy
  - matplotlib
  - notebook=6.5.4
  - jupyterlab=3.6.1
  - fonts-liberation  # Installs Liberation Sans and other Liberation fonts
  - fontconfig  # Helps with font detection
